from .images import IMAGE_CLASS_MAPPINGS, IMAGE_NAME_MAPPINGS
from .ipadapter import IPADAPTER_CLASS_MAPPINGS, IPADAPTER_NAME_MAPPINGS
from .masks import MASK_CLASS_MAPPINGS, MASK_NAME_MAPPINGS
from .misc import MISC_CLASS_MAPPINGS, MISC_NAME_MAPPINGS

NODE_CLASS_MAPPINGS = {}
NODE_DISPLAY_NAME_MAPPINGS = {}

NODE_CLASS_MAPPINGS.update(IPADAPTER_CLASS_MAPPINGS)
NODE_DISPLAY_NAME_MAPPINGS.update(IPADAPTER_NAME_MAPPINGS)

NODE_CLASS_MAPPINGS.update(MASK_CLASS_MAPPINGS)
NODE_DISPLAY_NAME_MAPPINGS.update(MASK_NAME_MAPPINGS)

NODE_CLASS_MAPPINGS.update(MISC_CLASS_MAPPINGS)
NODE_DISPLAY_NAME_MAPPINGS.update(MISC_NAME_MAPPINGS)

NODE_CLASS_MAPPINGS.update(IMAGE_CLASS_MAPPINGS)
NODE_DISPLAY_NAME_MAPPINGS.update(IMAGE_NAME_MAPPINGS)

print(NODE_CLASS_MAPPINGS)
print(NODE_DISPLAY_NAME_MAPPINGS)

WEB_DIRECTORY = './js'

__all__ = ['NODE_CLASS_MAPPINGS', 'NODE_DISPLAY_NAME_MAPPINGS', 'WEB_DIRECTORY']
