from .face_analysis import FACE_ANALYSIS_CLASS_MAPPINGS, FACE_ANALYSIS_NAME_MAPPINGS
from .files import FILE_CLASS_MAPPINGS, FILE_NAME_MAPPINGS
from .image_processing import IMAGE_PROCESSING_CLASS_MAPPINGS, IMAGE_PROCESSING_NAME_MAPPINGS
from .image_scale import IMAGE_SCALE_CLASS_MAPPINGS, IMAGE_SCALE_NAME_MAPPINGS
from .ipadapter import IPADAPTER_CLASS_MAPPINGS, IPADAPTER_NAME_MAPPINGS
from .masks import MASK_CLASS_MAPPINGS, MASK_NAME_MAPPINGS
from .misc import MISC_CLASS_MAPPINGS, MISC_NAME_MAPPINGS
from .schedule_sampler import SAMPLER_CLASS_MAPPINGS, SAMPLER_NAME_MAPPINGS

NODE_CLASS_MAPPINGS = {}
NODE_DISPLAY_NAME_MAPPINGS = {}

NODE_CLASS_MAPPINGS.update(IPADAPTER_CLASS_MAPPINGS)
NODE_DISPLAY_NAME_MAPPINGS.update(IPADAPTER_NAME_MAPPINGS)

NODE_CLASS_MAPPINGS.update(MASK_CLASS_MAPPINGS)
NODE_DISPLAY_NAME_MAPPINGS.update(MASK_NAME_MAPPINGS)

NODE_CLASS_MAPPINGS.update(MISC_CLASS_MAPPINGS)
NODE_DISPLAY_NAME_MAPPINGS.update(MISC_NAME_MAPPINGS)

NODE_CLASS_MAPPINGS.update(FACE_ANALYSIS_CLASS_MAPPINGS)
NODE_DISPLAY_NAME_MAPPINGS.update(FACE_ANALYSIS_NAME_MAPPINGS)


NODE_CLASS_MAPPINGS.update(IMAGE_SCALE_CLASS_MAPPINGS)
NODE_DISPLAY_NAME_MAPPINGS.update(IMAGE_SCALE_NAME_MAPPINGS)

NODE_CLASS_MAPPINGS.update(IMAGE_PROCESSING_CLASS_MAPPINGS)
NODE_DISPLAY_NAME_MAPPINGS.update(IMAGE_PROCESSING_NAME_MAPPINGS)

NODE_CLASS_MAPPINGS.update(FILE_CLASS_MAPPINGS)
NODE_DISPLAY_NAME_MAPPINGS.update(FILE_NAME_MAPPINGS)

NODE_CLASS_MAPPINGS.update(SAMPLER_CLASS_MAPPINGS)
NODE_DISPLAY_NAME_MAPPINGS.update(SAMPLER_NAME_MAPPINGS)


WEB_DIRECTORY = './js'

__all__ = ['NODE_CLASS_MAPPINGS', 'NODE_DISPLAY_NAME_MAPPINGS', 'WEB_DIRECTORY']
